NetMvc/NetMvc/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NetMvc.Models;

namespace NetMvc.Controllers
{
    public class CompanyController : Controller
    {
        private static List<CompanyViewModel> _companyViewModels = new List<CompanyViewModel>()
        {
            new CompanyViewModel(1, "Astra Graphia Teknologi", "logoAstraG.jpg", "Jl Bandung", 02132147747),
            new CompanyViewModel(2, "Telkomsel", "logoTsel.jpg", "Jl Gatot Subroto", 02144377789),
            new CompanyViewModel(3, "Astra Otoparts", "logoAstraO.jpg", "Jl Jakrata 2", 0213232999),
            new CompanyViewModel(4, "PUPR", "logoPupr.jpg", "Jl Presiden", 02155511222),
            new CompanyViewModel(5, "Pertamina", "logoPertamina.jpg", "Jl Kemerdekaan", 02188877711),
        };

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, CompanyName, Logo, Address, Telp")] CompanyViewModel company)
        {
            _companyViewModels.Add(company);
            return Redirect("List");
        }

        public IActionResult List()
        {
            return View(_companyViewModels);
        }

        public IActionResult Edit(int? id)
        {
            // find with lambda
            CompanyViewModel company = _companyViewModels.Find(x => x.Id.Equals(id));
            return View(company);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, CompanyName, Logo, Address, Telp")] CompanyViewModel company)
        {
            // hapus data lama
            CompanyViewModel companyOld = _companyViewModels.Find(x => x.Id.Equals(id));
            _companyViewModels.Remove(companyOld);

            // input data baru
            _companyViewModels.Add(company);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            // find with linq
            CompanyViewModel company = (
                    from p in _companyViewModels
                    where p.Id.Equals(id)
                    select p
                ).SingleOrDefault(new CompanyViewModel());
            return View(company);
        }


        public IActionResult Delete(int? id)
        {
            // find data dulu
            CompanyViewModel company = _companyViewModels.Find(x => x.Id.Equals(id));
            // remove from list
            _companyViewModels.Remove(company);

            return RedirectToAction(nameof(List));
        }
    }
}

NetMvc/NetMvc/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace NetMvc.Controllers
{
    public class LoginController : Controller
    {
        // GET: LoginController
        public ActionResult Index()
        {
            return View();
        }

        // GET: LoginController/SignUp
        public ActionResult SignUp()
        {
            return View();
        }

        // GET: LoginController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LoginController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoginController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoginController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

NetMvc/NetMvc/Controllers/ReportController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NetMvc.Models;
using System.Globalization;

namespace NetMvc.Controllers
{
    public class ReportController : Controller
    {
        private static List<ReportViewModel> _reportViewModels = new List<ReportViewModel>()
        {
            new ReportViewModel(1, "Agus Budiono", "1999-01-17" , "Work", "08.00", "17.00", "Develop Form Employee"),
            new ReportViewModel(2, "Siti Kholifah","1999-01-17" , "Work", "08.00", "17.00", "Develop Form Employee"),
            new ReportViewModel(3, "Banu Anugrah", "1999-01-17" , "Work", "08.00", "17.00", "Develop Form Employee"),
            new ReportViewModel(4, "Danang Setiawan", "1999-01-17" , "Work", "08.00", "17.00", "Develop Form Employee"),
            new ReportViewModel(5, "Rizki Jamaludin", "1999-01-17" , "Work", "08.00", "17.00", "Develop Form Employee"),
        };

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, FullName, Date, Shift, In, Out, Task")] ReportViewModel report)
        {
            _reportViewModels.Add(report);
            return Redirect("List");
        }

        public IActionResult List()
        {
            return View(_reportViewModels);
        }

        public IActionResult Edit(int? id)
        {
            // find with lambda
            ReportViewModel report = _reportViewModels.Find(x => x.Id.Equals(id));
            return View(report);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, FullName, Date, Shift, In, Out, Task")] ReportViewModel report)
        {
            // hapus data lama
            ReportViewModel reportOld = _reportViewModels.Find(x => x.Id.Equals(id));
            _reportViewModels.Remove(reportOld);

            // input data baru
            _reportViewModels.Add(report);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            // find with linq
            ReportViewModel report = (
                    from p in _reportViewModels
                    where p.Id.Equals(id)
                    select p
                ).SingleOrDefault(new ReportViewModel());
            return View(report);
        }


        public IActionResult Delete(int? id)
        {
            // find data dulu
            ReportViewModel report = _reportViewModels.Find(x => x.Id.Equals(id));
            // remove from list
            _reportViewModels.Remove(report);

            return RedirectToAction(nameof(List));
        }
    }
}

NetMvc/NetMvc/Controllers/SetupController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NetMvc.Models;
using System.Globalization;

namespace NetMvc.Controllers
{
    public class SetupController : Controller
    {
        private static List<SetupViewModel> _setupViewModels = new List<SetupViewModel>()
        {
            new SetupViewModel(1, "Agus Budiono", "15-10-1999", "15-10-1999" , "AGIT", "James", "Dodi"),
            new SetupViewModel(2, "Siti Kholifah", "15-10-1999", "15-10-1999" , "AGIT", "James", "Dodi"),
            new SetupViewModel(3, "Banu Anugrah", "15-10-1999", "15-10-1999" , "AGIT", "James", "Dodi"),
            new SetupViewModel(4, "Danang Setiawan", "15-10-1999", "15-10-1999" , "AGIT", "James", "Dodi"),
            new SetupViewModel(5, "Rizki Jamaludin", "15-10-1999", "15-10-1999" , "AGIT", "James", "Dodi"),
        };

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save([Bind("Id, FullName, StartDate, EndDate, Company, ReportTo1, ReportTo2")] SetupViewModel setup)
        {
            _setupViewModels.Add(setup);
            return Redirect("List");
        }

        public IActionResult List()
        {
            return View(_setupViewModels);
        }

        public IActionResult Edit(int? id)
        {
            // find with lambda
            SetupViewModel setup = _setupViewModels.Find(x => x.Id.Equals(id));
            return View(setup);
        }

        [HttpPost]
        public IActionResult Update(int id, [Bind("Id, FullName, StartDate, EndDate, Company, ReportTo1, ReportTo2")] SetupViewModel setup)
        {
            // hapus data lama
            SetupViewModel setupOld = _setupViewModels.Find(x => x.Id.Equals(id));
            _setupViewModels.Remove(setupOld);

            // input data baru
            _setupViewModels.Add(setup);
            return Redirect("List");
        }

        public IActionResult Details(int id)
        {
            // find with linq
            SetupViewModel setup = (
                    from p in _setupViewModels
                    where p.Id.Equals(id)
                    select p
                ).SingleOrDefault(new SetupViewModel());
            return View(setup);
        }


        public IActionResult Delete(int? id)
        {
            // find data dulu
            SetupViewModel setup = _setupViewModels.Find(x => x.Id.Equals(id));
            // remove from list
            _setupViewModels.Remove(setup);

            return RedirectToAction(nameof(List));
        }
    }
}

NetMvc/NetMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetMvc.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: rgb(255,255,255);
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%,-50%);
            left: 50%;
            top: 50%;
        }

            .background .shape {
                height: 200px;
                width: 200px;
                position: absolute;
                border-radius: 50%;
            }

        .shape:first-child {
            background: linear-gradient( #1845ad, #23a2f6 );
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient( to right, #ff512f, #f09819 );
            right: -30px;
            bottom: -80px;
        }

        .form-login {
            height: 520px;
            width: 400px;
            background-color: rgba(255,255,255,0.13);
            position: absolute;
            transform: translate(-50%,-50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255,255,255,0.1);
            box-shadow: 0 0 40px rgba(8,7,16,0.6);
            padding: 50px 35px;
        }

            form * {
                font-family: 'Poppins',sans-serif;
                color: steelblue;
                letter-spacing: 0.5px;
                outline: none;
                border: none;
            }

            form h3 {
                font-size: 32px;
                font-weight: 500;
                line-height: 42px;
                text-align: center;
            }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(223, 211, 217, 0.4);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
            margin-bottom:20px;
        }

        ::placeholder {
            color: steelblue;
        }

        .button-login {
            margin-top: 30px;
            width: 100%;
            background-color: rgba(223, 211, 217, 0.4);
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

            .social div {
                background: red;
                width: 150px;
                border-radius: 3px;
                padding: 5px 10px 10px 5px;
                background-color: rgba(223, 211, 217, 0.4);
                color: steelblue;
                text-align: center;
            }

                .social div:hover {
                    background-color: rgba(255,255,255,0.47);
                }

            .social .fb {
                margin-left: 25px;
            }

            .social i {
                margin-right: 4px;
            }

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="List">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Setup" asp-action="List">Setup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="List">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="List">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="List">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="SignUp">Sign Up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NetMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>